services:
  db-postgres:
    image: bitnami/postgresql
    ports:
      - 5432:5432
    environment:
      - POSTGRESQL_USERNAME=docker
      - POSTGRESQL_PASSWORD=unipet
      - POSTGRESQL_DATABASE=unipetdb
